twitter:
  consumer_key: sVgTfZRTJ2CBaUx5CAd41g
  consumer_secret: pkfX0EmiBoIxIhCFWohzcHnGHmdEjYe7PxO53zmvu8
  oauth_token: 17370468-rcysNoqeq98ezYs4wtpWpnCkCQIM95yy51YnQak2o
  oauth_token_secret: 27VdDIjmMzTO5C28FNjcaPDulGAgz2jMKzvB53Q1ZkYXI
